### ISSUE TITLE
ブロック一覧に公開状態を表示する

### ISSUE THREAD

**Issue by RyujiAMANO** [NetCommons3/Cabinets#19]
現在仮実装になってるので、BlockIndexヘルパが対応したら公開状態をちゃんと表示するように変更する

**Comment by s-nakajima** [comment]
あ、このIssue、https://github.com/NetCommons3/Cabinets/pull/24/commits/6ccb0bbe5c8376f25b36b9bfd84b8255b10661eb といっしょにやっちゃいました。

**Comment by RyujiAMANO** [comment]
サンクス！
